steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull asia-southeast2-docker.pkg.dev/bdi-onprem/custom-prediction-routine-sdk/output-cpr:latest
      docker tag asia-southeast2-docker.pkg.dev/bdi-onprem/custom-prediction-routine-sdk/output-cpr:latest \
                 asia-southeast2-docker.pkg.dev/me-data-internal-sandbox/custom-prediction-routine-sdk/output-cpr:latest
      docker push asia-southeast2-docker.pkg.dev/me-data-internal-sandbox/custom-prediction-routine-sdk/output-cpr:latest
