# Define variables as custom substitutions. They MUST be prefixed with an underscore (_).
substitutions:
  # Source project details
  _SOURCE_PROJECT_ID: 'bdi-onprem'
  _SOURCE_AR_HOST: 'asia-southeast2-docker.pkg.dev'
  _SOURCE_REPOSITORY: 'custom-prediction-routine-sdk'
  
  # Destination project details
  _DEST_PROJECT_ID: 'me-data-internal-sandbox'
  _DEST_AR_HOST: 'asia-southeast2-docker.pkg.dev'
  _DEST_REPOSITORY: 'custom-prediction-routine-sdk'
  
  # Image filtering
  _IMAGE_PREFIX: 'image_docker'

steps:
# 1. Pull and Push Images with a Filter
- name: 'gcr.io/cloud-builders/gcloud'
  id: Copy_Images
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Configure Docker for cross-project access
    # Use standard environment variables (defined in 'env' block below)
    gcloud auth configure-docker ${SOURCE_AR_HOST} --quiet
    gcloud auth configure-docker ${DEST_AR_HOST} --quiet

    # Base URL for listing images in the source project
    SOURCE_REGISTRY_PATH=${SOURCE_AR_HOST}/${SOURCE_PROJECT_ID}/${SOURCE_REPOSITORY}
    DEST_REGISTRY_PATH=${DEST_AR_HOST}/${DEST_PROJECT_ID}/${DEST_REPOSITORY}

    echo "Listing images in source: ${SOURCE_REGISTRY_PATH}"

    # List images, filter by prefix, and extract the full image name
    gcloud artifacts docker images list ${SOURCE_REGISTRY_PATH} \
      --include-tags \
      --format='value(format("{0}:{1}", PACKAGE, TAG))' \
      --filter="PACKAGE~^${IMAGE_PREFIX}" \
      --limit=9999 \
      > /workspace/images_to_copy.txt

    if [ ! -s /workspace/images_to_copy.txt ]; then
        echo "No images found with prefix ${IMAGE_PREFIX}. Exiting."
        exit 0
    fi

    echo "Found images to copy:"
    cat /workspace/images_to_copy.txt

    # Loop through each image and copy it
    while IFS= read -r FULL_IMAGE_NAME
    do
      if [ -z "$FULL_IMAGE_NAME" ]; then continue; fi

      # Full path of the source image
      SOURCE_IMAGE_TAG="${SOURCE_REGISTRY_PATH}/${FULL_IMAGE_NAME}"

      # Use the same image/tag name for the destination
      DEST_IMAGE_TAG="${DEST_REGISTRY_PATH}/${FULL_IMAGE_NAME}"

      echo "Pulling ${SOURCE_IMAGE_TAG}"
      docker pull "${SOURCE_IMAGE_TAG}"

      echo "Tagging ${FULL_IMAGE_NAME} for destination project"
      docker tag "${SOURCE_IMAGE_TAG}" "${DEST_IMAGE_TAG}"

      echo "Pushing ${DEST_IMAGE_TAG}"
      docker push "${DEST_IMAGE_TAG}"

      echo "Completed push of ${DEST_IMAGE_TAG}"
    done < /workspace/images_to_copy.txt
  env:
    # Map the Cloud Build substitution variables (prefixed with _) 
    # to standard environment variables for the shell script to use.
  - 'HOME=/root'
  - 'SOURCE_PROJECT_ID=$_SOURCE_PROJECT_ID'
  - 'SOURCE_AR_HOST=$_SOURCE_AR_HOST'
  - 'SOURCE_REPOSITORY=$_SOURCE_REPOSITORY'
  - 'DEST_PROJECT_ID=$_DEST_PROJECT_ID'
  - 'DEST_AR_HOST=$_DEST_AR_HOST'
  - 'DEST_REPOSITORY=$_DEST_REPOSITORY'
  - 'IMAGE_PREFIX=$_IMAGE_PREFIX'

options:
  # Required when running with a custom Service Account
  logging: CLOUD_LOGGING_ONLY
