options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # The 'IMAGE_NAME: prj' caused the error because custom substitutions
  # must start with an underscore (e.g., '_IMAGE_NAME').
  # Since you don't use this substitution in the script, it's safer to remove it.
  # If you want to use project IDs as substitutions, use the existing
  # _PROJECT_TARGET and _PROJECT_SOURCE pattern.

steps:
  # Step 1: Copy docker images from Artifact Registry source to target
  - id: copy-docker-images-source-project
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        set -e

        # --- Configuration Variables ---
        REPO_NAME_SOURCE="custom-prediction-routine-sdk"
        REPO_NAME_TARGET="custom-prediction-routine-sdk"
        
        # Array of image names to copy
        IMAGE_NAMES=(
          "image_docker_1"
          "image_docker_2"
          "image_docker_3"
        )
        
        # Define Project IDs based on your actual source/target structure
        # NOTE: I am hardcoding the project IDs here as they were not provided
        # in the substitutions block. If you want to use substitutions,
        # you need to define them in the substitutions block and reference them 
        # using '$_VARIABLE_NAME'.
        PROJECT_SOURCE="bdi-onprem"
        PROJECT_TARGET="me-data-internal-sandbox"
        
        # --- Loop and Copy Images ---
        
        for IMAGE_NAME in "${IMAGE_NAMES[@]}"; do
            echo "---"
            echo "[STEP] Processing image: ${IMAGE_NAME}"
            
            # Construct Source and Destination Image URIs
            # Note: Using the PROJECT_SOURCE/TARGET variables defined above
            SRC_IMAGE="asia-southeast2-docker.pkg.dev/${PROJECT_SOURCE}/${REPO_NAME_SOURCE}/${IMAGE_NAME}:latest"
            DEST_IMAGE="asia-southeast2-docker.pkg.dev/${PROJECT_TARGET}/${REPO_NAME_TARGET}/${IMAGE_NAME}:latest"

            echo "[INFO] Source image : ${SRC_IMAGE}"
            echo "[INFO] Dest image   : ${DEST_IMAGE}"
            
            # 1. Pull the image from the source project
            echo "[ACTION] Pulling image..."
            docker pull "${SRC_IMAGE}"
            
            # 2. Tag the image for the target project
            echo "[ACTION] Tagging image..."
            docker tag "${SRC_IMAGE}" "${DEST_IMAGE}"
            
            # 3. Push the tagged image to the target project
            echo "[ACTION] Pushing image..."
            docker push "${DEST_IMAGE}"
            
            echo "[SUCCESS] Image '${IMAGE_NAME}' successfully copied to target project 🎉"
        done

        echo "---"
        echo "[SUMMARY] All specified images have been processed."
        echo "----------------------------------------"
